### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/UnsupervisedDecomposition/XLM/data/hotpot-orig/qid2passage_entities.json'

### ISSUE THREAD

**Issue by minhson-kaist** [facebookresearch/UnsupervisedDecomposition#10]
Hi,

When I tried to execute command:
`python add_umt_subqs_subas_to_q_squad_format_new.py --subqs_dir data/hotpot.umt.all.model=$MODEL_NO.st=$ST.beam=$BEAM.lp=$LP.seed=$SEED --splits train dev --num_shards 1 --model_dir $MODEL_DIR --sample_temperature $ST --beam $BEAM --length_penalty $LP --seed $SEED --subsample_data --use_easy --use_squad $FLAGS`

I got the error: `FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/son/UnsupervisedDecomposition/XLM/data/hotpot-orig/qid2passage_entities.json'`

I check previous scripts and I cannot find how I can generate `qid2passage_entities.json` file.
Could you specify how to create that file?

Thanks,

**Comment by ethanjperez** [comment]
Hi @detuvoldo, that file is only necessary to run our "random entity as subanswer" baseline (Table 2 right in [our paper](https://arxiv.org/pdf/2002.09758.pdf)), so you can safely comment out any lines that use/require it.

**Comment by minhson-kaist** [comment]
@ethanjperez  thanks for pointing out that. I guessed this file was used for additional experiments so I did as you suggest.

**Comment by ethanjperez** [comment]
For future reference, you can download the missing file like so:
```bash
cd $MAIN_DIR/XLM/data/hotpot-orig/
wget http://dl.fbaipublicfiles.com/UnsupervisedDecomposition/data/qid2passage_entities.json .
```
