### ISSUE TITLE
About data/hotpot_orig/hotpot_dev_1hop_solv_nonsolv.json file used by hotot_evaluate_v1.py in 97 line doesn't find

### ISSUE THREAD

**Issue by cmjxll** [facebookresearch/UnsupervisedDecomposition#2]
hi:
    I dont't find hotpot_dev_1hop_solv_nonsolv.json in data/hotpot_orig dir.  After  checking download_data.sh,  I find no dowloading the file.  Could you tell how to acquire the file. Thanks for your great work!

**Comment by ethanjperez** [comment]
Hi @cmjxll, thanks for pointing this out. You can find the file here: https://drive.google.com/file/d/1l8qdapvRI2VCdLiSJ__D8p6tIOzm2t_e/view?usp=sharing

The file is adapted from the Min et al. 2019 (DecompRC) and provides the question IDs for questions that a single-hop BERT model can't answer, so it's mostly for analysis purposes (and not strictly necessary). Thanks!
