### ISSUE TITLE
Is it working on Windows system?

### ISSUE THREAD

**Issue by minhnguyenth** [facebookresearch/UnsupervisedDecomposition#3]
I have been trying to install the system on Windows 10 without success. I got stuck at the step install fastBPE package. It  requires <sys/mman.h > file but Windows does not have this file. Is there work around way?

**Comment by patrick-s-h-lewis** [comment]
Hi Minh Nguyen,

Getting fastBPE to work on windows is out of scope right now, I hope you can find a solution!

Patrick
