### ISSUE TITLE
Processed Common Crawl Questions

### ISSUE THREAD

**Issue by xiangyue9607** [facebookresearch/UnsupervisedDecomposition#6]
Hello,

I notice that in the paper you augment the data with the questions from Common Crawl. It seems that I do not find those processed questions / raw files in the repo. 

Thank you so much!

**Comment by patrick-s-h-lewis** [comment]
Hi Xiang Yue,

We're uploading additional data in the next couple of days, including the data used to build the pseudo-decompositions, check back again in a few days :)

Patrick

**Comment by ethanjperez** [comment]
@xiangyue9607 we've added the data to the repo. Let us know if you have other questions!
