### ISSUE TITLE
The folder to put custom training data

### ISSUE THREAD

**Issue by minhson-kaist** [facebookresearch/UnsupervisedDecomposition#8]
Hi,

I want to use your code to train my own question decomposition model, with my own questions and sub-questions data. Nevertheless, it is quite difficult for me to look up the folder to replace the training data you used with my own training data. 

Can you help me specify the folder to put my own training data in?

Thank you.

**Comment by ethanjperez** [comment]
Hi @detuvoldo, thanks for your question. Just format the multi-hop questions (one question per line, in files named `train.mh`/`valid.mh`/`test.mh`) and single-hop questions (one question per line, in the same order as for multi-hop questions, in files named `train.sh`/`valid.sh`/`test.sh`). Place those questions in a directory like `data/umt/$DATA_FOLDER`. Then, you can preprocess the questions like:
```bash
for SPLIT in valid train; do
    ./get-data-mt.sh --src mh --tgt sh --reload_codes dumped/xlm_en/codes_en --reload_vocab dumped/xlm_en/vocab_en --data_folder $DATA_FOLDER --split $SPLIT
done
```

Then, you should be able to train a model with unsupervised seq2seq learning, following the instructions in the README [here](https://github.com/facebookresearch/UnsupervisedDecomposition#unsupervised-decomposition-training) (just use the instructions starting from "Then, train an Unsupervised Seq2Seq..." but with your new `DATA_FOLDER` variable).

Hope that helps! Let us know if you have other questions.

**Comment by minhson-kaist** [comment]
Hi @ethanjperez ,
Thanks for your detailed instruction. When I follow your instruction, then follow the training instruction, an error happened at 
NUM_TRAIN=`wc -l < data/umt/$DATA_FOLDER/processed/train.mh`.

The detailed error is: 
`bash: data/umt/qg/processed/train.mh: No such file or directory`.

I checked `processed` folder, and I found that the bash file did not process the `mh` and `sh` file, and `.pth` files are missing in `processed` folder.

**Comment by ethanjperez** [comment]
To preprocess the data, try instead (from the `UnsupervisedDecomposition/XLM` directory):

```bash
./get-data-mt.sh --src mh --tgt sh --reload_codes dumped/xlm_en/codes_en --reload_vocab dumped/xlm_en/vocab_en --data_folder $DATA_FOLDER
```

I think the previous command I sent you might not have run properly, because I included an extra flag (`--split`)

**Comment by minhson-kaist** [comment]
> To preprocess the data, try instead (from the `UnsupervisedDecomposition/XLM` directory):
> 
> ```shell
> ./get-data-mt.sh --src mh --tgt sh --reload_codes dumped/xlm_en/codes_en --reload_vocab dumped/xlm_en/vocab_en --data_folder $DATA_FOLDER
> ```
> 
> I think the previous command I sent you might not have run properly, because I included an extra flag (`--split`)

This script is exactly the same as in ` create_pseudo_decompositions.sh`. I tried with it before but it raised an error:
`/home/ubuntu/son/UnsupervisedDecomposition/XLM/tools/fastBPE/fast: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /home/ubuntu/son/UnsupervisedDecomposition/XLM/tools/fastBPE/fast)`

When I tried with hotpotQA original data (simply re-run your script without any modifications), no error occurred. Seems like there are some differences between my data (actually hotpotQA data but processed in a different way) and your data.
